# 배열의 연산

In [5]:
import numpy as np
x = np.arange(1, 10001)
y = np.arange(10001, 20001)

In [6]:
z = np.zeros_like(x)
for i in range(10000):
    z[i] = x[i] + y[i]

In [8]:
z[:10]
#여기까지는 벡터화 연산을 사용하지 않은 것

array([10002, 10004, 10006, 10008, 10010, 10012, 10014, 10016, 10018,
       10020])

In [10]:
#벡터화 연산을 하면 훨씬 연산속도도 빠르고 좋다
z = x+y
z

array([10002, 10004, 10006, ..., 29996, 29998, 30000])

In [11]:
#사칙연산 뿐만아니라 비교 논리 연산도 가능
a = np.array([1,2,3,4])
b = np.array([4,2,2,4])

In [12]:

a==b

array([False,  True, False,  True])

In [13]:
a>=b

array([False,  True,  True,  True])

In [15]:
#각각 비교하는 것이 아니라 모든 원소들이 다 같은지 알고 싶다면 all을 사용하면 된다.
a = np.array([1, 2, 3, 4])
b = np.array([4, 2, 2, 4])
c = np.array([1, 2, 3, 4])

In [17]:
np.all(a ==b)

False

In [18]:
np.all(a==c)

True

In [19]:
#지수 함수나 로그함수도 벡터화 연산을 지원한다
a = np.arange(5)
a

array([0, 1, 2, 3, 4])

In [20]:
np.exp(a)

array([ 1.        ,  2.71828183,  7.3890561 , 20.08553692, 54.59815003])

In [21]:
10 ** a

array([    1,    10,   100,  1000, 10000], dtype=int32)

In [22]:
np.log(a + 1)

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791])

In [24]:
#스칼라와 벡터/행렬의 곱도 선형 대수에서 사용하는 식과 NumPy 코드가 일치한다.
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [25]:
100 * x

array([  0, 100, 200, 300, 400, 500, 600, 700, 800, 900])

In [28]:
x = np.arange(12)

In [30]:
x.reshape(3,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

# numpy에서는 브로드 캐스팅이 가능하다

In [31]:
#브로드캐스팅은 작은 차원의 숫자를 큰 차원의 숫자로 변환 시켜서 연산 해주는 기능이다
x = np.arange(5)
x

array([0, 1, 2, 3, 4])

In [32]:
y = np.ones_like(x)
y


array([1, 1, 1, 1, 1])

In [33]:
x + y

array([1, 2, 3, 4, 5])

In [35]:
x + 1
#1,1,1,1,1과 1의 합의 결과가 같다는 것을 보여준다

array([1, 2, 3, 4, 5])

In [41]:
#브로드캐스팅 차원이 높은 부분도 적용된다.
x = np.vstack([range(7)[i:i + 3] for i in range(5)])
x


array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4],
       [3, 4, 5],
       [4, 5, 6]])

In [42]:
y = np.arange(6)[:, np.newaxis]
y
y.reshape(2,3)

array([[0, 1, 2],
       [3, 4, 5]])

In [44]:
x + y
#행 열 1 by x나 x by 1이 아니면 브로드 캐스팅이 일어나지 않는다

ValueError: operands could not be broadcast together with shapes (5,3) (6,1) 

# 차원 축소 연산

In [46]:
#한 배열안에 있는 원소들을 하나로 연산하는 것을 차원 축소 연산이라고 한다.
x= np.array([1,2,3,4])

In [47]:
np.sum(x)

10

In [48]:
x = np.array([1, 3, 2])

In [49]:
x.min()

1

# 2차원 이상인 경우에는 어느 차원으로 계산을 할 지를 axis인수로 정한다

In [50]:
x = np.array([[1, 1], [2, 2]])
x

array([[1, 1],
       [2, 2]])

In [51]:
x.sum(axis=0)  

array([3, 3])

In [66]:
z = np.arange(30)
k=z.reshape(5,6)

In [67]:
k.max()

29

In [68]:
k.sum(axis=0)

array([60, 65, 70, 75, 80, 85])

In [69]:
k.sum(axis=1)

array([ 15,  51,  87, 123, 159])

# 정렬

In [ ]:
#sort 명령이나 메서드를 사용하여 배열 안의 원소를 정렬할 수 있다 


In [70]:
a = np.array([[4,  3,  5,  7],
              [1, 12, 11,  9],
              [2, 15,  1, 14]])
a

array([[ 4,  3,  5,  7],
       [ 1, 12, 11,  9],
       [ 2, 15,  1, 14]])

In [76]:
np.sort(a)  # axis=-1 또는 axis=1 과 동일  디폴트 값이 1이다

array([[ 3,  4,  5,  7],
       [ 1,  9, 11, 12],
       [ 1,  2, 14, 15]])

In [77]:
np.sort(a,axis=0)

array([[ 1,  3,  1,  7],
       [ 2, 12,  5,  9],
       [ 4, 15, 11, 14]])

In [80]:
#sort 메서드는 값이 바뀌는 메서드이므로 주의를 기울여야 한다
#만약 자료를 정렬하는 것이 아니라 순서만 알고 싶다면 argsort 명령을 사용한다.
a = np.array([42, 38, 12, 25])
j = np.argsort(a)
j

array([2, 3, 1, 0], dtype=int64)

In [84]:
x=np.array([[  1,    2,    3,    4],
       [ 46,   99,  100,   71],
       [ 81,   59,   90,  100]])
x.ndim

2

In [87]:
np.sort(x,axis=0)
x

array([[  1,   2,   3,   4],
       [ 46,  99, 100,  71],
       [ 81,  59,  90, 100]])

In [ ]:
#연습문제 모르게씀