# Numpy 배열

In [1]:
#많은 숫자를 하나의 변수에 넣고 관리할떄 리스트는 속도가 느리고 메모리 많이 잡아 먹음. 해결위해 배열을 쓴다
#배열은 모든 원소가 같은 자료형이다, 원소의 개수를 바꿀 수 없다.

import numpy as np


In [5]:
ar = np.array([0,1,2,3,4,5,6,7,8,9])
ar
#각원소들이 같은 자료형이기 때문에 실행이 빠르다

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
type(ar)
#자료형이 ndarray로 나온다

numpy.ndarray

In [7]:
#벡터화 연산
data = [0,1,2,3,4,5,6,7,8,9]

In [8]:
answer = []
for di in data:
    answer.append(2 * di)
answer

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]

In [14]:
data *= 2
data
#리스트는 2를 곱해도 개수가 늘어나지 연산이 되지 않는다.

[0,
 1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 0,
 1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 0,
 1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 0,
 1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9]

In [9]:
[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]

In [10]:
#위를 벡터화 연산을 하면 더 빠르게 할 수 있다.
x = np.array(data)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
2 * x

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [15]:
a = np.array([1, 2, 3])
b = np.array([10, 20, 30])

In [16]:
2 * a + b

array([12, 24, 36])

In [17]:
a == 2

array([False,  True, False])

In [18]:
b > 10

array([False,  True,  True])

In [20]:
(a == 2) & (b > 10)
#선형대수에 주로 쓰인다

array([False,  True, False])

In [21]:
#2차 배열 -> 행렬
c = np.array([[0,1,2,],[3,4,5]])

In [22]:
c

array([[0, 1, 2],
       [3, 4, 5]])

In [25]:
#행의 개수
len(c)

2

In [26]:
type(c)

numpy.ndarray

In [28]:
#열의 개수
len(c[0])

3

# 연습문제 4.1.1

In [30]:
moonsu= np.array([[10,20,30,40],[50,60,70,80]])

In [31]:
moonsu

array([[10, 20, 30, 40],
       [50, 60, 70, 80]])

In [33]:
#3차 배열
d = np.array([[[1, 2, 3, 4],
               [5, 6, 7, 8],
               [9, 10, 11, 12]],
              [[11, 12, 13, 14],
               [15, 16, 17, 18],
               [19, 20, 21, 22]]]) 
#위는 (2,3,4) 배열이다

In [35]:
#3차원 배열의 행,열,깊이
len(d), len(d[0]), len(d[0][0])

(2, 3, 4)

In [38]:
#배열의 차원가 크기를 알 수 있는 쉬운방법은 ndim과 shape를 이용하는 것이다
a = np.array([1,2,3])
print(a.ndim)
#배열의 차원

1


In [39]:
print(a.shape)
#배열의 크기

(3,)


In [40]:
c = np.array([[0, 1, 2], [3, 4, 5]])
print(c.ndim)
print(c.shape)

2
(2, 3)


In [41]:
print(d.ndim)
print(d.shape)

3
(2, 3, 4)


In [49]:
#배열의 인덱싱
#1차 배열의 인덱싱은 list와 같다
a = np.array([0,1,2,3,4])

In [43]:
a[2]

2

In [56]:
a[-2]
#-로 인덱싱을 세면 뒤에서 부터 센다.

3

In [58]:
a = np.array([[0, 1, 2], [3, 4, 5]])
a

array([[0, 1, 2],
       [3, 4, 5]])

In [59]:
a[0,0]
#첫번째 행 첫번쨰 열

0

In [60]:
a[-1, -1]  # 마지막 행의 마지막 열

5

In [61]:
#배열 슬라이싱
#배열에서 복수개의 접근하려면 슬라이싱을 이용한다
a= np.array([[0,1,2,3],[4,5,6,7]])
a

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [62]:
a[0, :]

array([0, 1, 2, 3])

In [63]:
a[:, 1]  # 두번째 열 전체

array([1, 5])

In [64]:
a[1, 2:]  # 두번째 행의 3번째 열부터 끝열까지

array([6, 7])

# 연습문제 4.1.2

In [65]:
m = np.array([[ 0,  1,  2,  3,  4],
              [ 5,  6,  7,  8,  9],
              [10, 11, 12, 13, 14]])

In [69]:
m[1, 2]

7

In [70]:
m[-1,-1]

14

In [78]:
m[1,1],m[1,2]

(6, 7)

In [79]:
m[1,2],m[2,2]

(7, 12)

In [81]:
m[0,3:],m[1,3:]

(array([3, 4]), array([8, 9]))

In [83]:
#팬시 인덱싱
#배열의 질의 기능을 수행한다
a = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
idx = np.array([True, False, True, False, True,
                False, True, False, True, False])
a[idx]
#짝수만 골라내고 싶을 떄 짝수에만 true 를 넣는다

array([0, 2, 4, 6, 8])

In [84]:
#조건문 연산도 가능하다
a % 2

array([0, 1, 0, 1, 0, 1, 0, 1, 0, 1], dtype=int32)

In [85]:
a % 2 ==0

array([ True, False,  True, False,  True, False,  True, False,  True,
       False])

In [87]:
a[a % 2 == 0]
#이는 결국 true만 뽑으라는 말이 된다.

array([0, 2, 4, 6, 8])

In [91]:
a = np.array([11, 22, 33, 44, 55, 66, 77, 88, 99])
idx = np.array([0, 2, 4, 6, 8])
a[idx]
#홀수만 뽑아내기
#위처럼 bulling도 가능하지만 단순이 인덱스만 넣어서 뽑을 수도 있다. -> 굳이 어렵게 알고리즘을 만들지 않아도 됨

array([11, 33, 55, 77, 99])

In [92]:
a = np.array([11, 22, 33, 44, 55, 66, 77, 88, 99])
idx = np.array([0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2])
a[idx]
#원래는 배열인덱스가 배열크기와 같아야 되지만 중복 될 때는 원래 크기를 초과하여도 된다.

array([11, 11, 11, 11, 11, 11, 22, 22, 22, 22, 22, 33, 33, 33, 33, 33])

In [93]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [95]:
#배열의 인덱싱은 다차원 배열에서도 가능하다

a[1:, [True, False, False, True]]

array([[ 5,  8],
       [ 9, 12]])

# 연습문제 4.1.3

In [96]:
x = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10,
              11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [99]:
idx = np.array([2,5,8,11,14,17,])

In [100]:
x[idx]

array([ 3,  6,  9, 12, 15, 18])

In [102]:
x[x % 4 == 1]

array([ 1,  5,  9, 13, 17])

In [109]:
a=x[x % 3 ==0] 
b=x[x % 4 ==1]

In [117]:
x[(x % 3 ==0) & (x % 4 ==1)] 
#헤매다가 성공

array([9])