# 배열의 생성과 변형

In [2]:
import numpy as np
#만들어진 배열의 자료형을 알아내려면 dtype 속성을 이용한다
x = np.array([1,2,3])

In [3]:
x.dtype

dtype('int32')

In [4]:
x = np.array([1.0, 2.0, 3.0])
x.dtype

dtype('float64')

In [5]:
x = np.array([1, 2, 3.0])
x.dtype

dtype('float64')

In [7]:

#dtype 접두사	설명	사용 예
#b	불리언	b (참 혹은 거짓)
#i	정수	i8 (64비트)
#u	부호 없는 정수	u8 (64비트)
#f	부동소수점	f8 (64비트)
#c	복소 부동소수점	c16 (128비트)
#O	객체	0 (객체에 대한 포인터)
#S	바이트 문자열	S24 (24 글자)
#U	유니코드 문자열	U24 (24 유니코드 글자)
#앞의 알파벳은 형태를 뜻하고 숫자는 크기를 뜻한다
x = np.array([1,2,3], dtype='f')
x.dtype

dtype('float32')

In [8]:
x[0] + x[1]
#자료형에 맞춰서 알아서 계산해줌

3.0

In [9]:
x = np.array([1, 2, 3], dtype='U')
x.dtype

dtype('<U1')

In [10]:
x[0] + x[1]

'12'

In [12]:
#무한대를 표현하기위한 np.inf와 정의할 수 없는 숫자를 나타내는 np.nan
np.array([0, 1, -1, 0]) / np.array([1, 0, 0, 0])
#1/0은 무한대로 0/0은 nan으로 뜬다

C:\Users\korewa\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: RuntimeWarning: divide by zero encountered in true_divide
  
C:\Users\korewa\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: RuntimeWarning: invalid value encountered in true_divide
  


array([  0.,  inf, -inf,  nan])

In [13]:
np.log(0)

C:\Users\korewa\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


-inf

In [14]:
np.exp(-np.inf)

0.0

# 여러가지 배열 생성

In [15]:
#zeros명령은 배열 전부를 0으로 해준다
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [16]:
b = np.zeros((2, 3))
b

array([[0., 0., 0.],
       [0., 0., 0.]])

In [17]:
c = np.zeros((5, 2), dtype="i")
c

array([[0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0]], dtype=int32)

In [18]:
d = np.zeros(5, dtype="U4")
d

array(['', '', '', '', ''], dtype='<U4')

In [19]:
#해당된 크기보다 큰 걸 입력하면 잘릴수 있다.
d[0] = "abc"
d[1] = "abcd"
d[2] = "ABCDE"
d

array(['abc', 'abcd', 'ABCD', '', ''], dtype='<U4')

In [21]:
#0이아닌 1로 초기화 시킨 배열을 만드려면 np.ones를 이용한다
e = np.ones((2, 3, 4), dtype="i8")
e

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int64)

In [25]:
#만약 튜플의 크기를 정해주지 않고 앞에 다른 것과 똑같이 하고 싶다면 np.ones_like를 쓴다
f = np.ones_like(d, dtype="f")
f

array([1., 1., 1., 1., 1.], dtype=float32)

In [26]:
#배열이 커지만 초기화 하는데 오래걸린다. 그래서 배열을 만들기만 하고 초기화를 하지 않을 수 도 있다.
g = np.empty((4, 3))
g

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [29]:
#arange 명령은 NumPy 버전의 range 명령이라고 볼 수 있다. 특정한 규칙에 따라 증가하는 수열을 만든다.
np.arange(20)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [31]:
#시작, 끝, 수열의 크기
np.arange(3, 21, 2)

array([ 3,  5,  7,  9, 11, 13, 15, 17, 19])

In [33]:
#linspace 명령이나 logspace 명령은 선형 구간 혹은 로그 구간을 지정한 구간의 수만큼 분할한다.
#100을 5등분으로 분할 시킨것
np.linspace(0, 100, 5) 

array([  0.,  25.,  50.,  75., 100.])

In [36]:
np.logspace(0, 100, 5)

array([1.e+000, 1.e+025, 1.e+050, 1.e+075, 1.e+100])

# 전치 연산

In [37]:
A = np.array([[1, 2, 3], [4, 5, 6]])
A

array([[1, 2, 3],
       [4, 5, 6]])

In [40]:
A.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [41]:
a = np.arange(12)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [46]:
#reshape로 생겨 먹은 모양을 바꿀 수 있다.
b=a.reshape(3,4)
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [47]:
a.reshape(3, -1)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [48]:
a.reshape(2, 2, -1)

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])

In [49]:
#다차원 배열을 무조건 1차원으로 펼치기 위해서는 flatten 나 ravel 메서드를 사용한다.
a.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [52]:

b=a.ravel()

In [54]:
#newaxis문으로 원하는 행이나 열쪽으로 차원만 1증가 시킬 수 있다.
b[np.newaxis,:]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11]])

# 배열 연결

In [55]:
#행의 수나 열의 수가 같을 때 두개 연결 시킬때 쓸수 있는 함수가 몇가지 있다

In [61]:
#hstack은 가로로 붙인다.
a1 = np.ones((2, 2))
a1

array([[1., 1.],
       [1., 1.]])

In [62]:
a2 = np.zeros((2, 2))
a2

array([[0., 0.],
       [0., 0.]])

In [63]:
np.hstack([a1, a2])

array([[1., 1., 0., 0.],
       [1., 1., 0., 0.]])

In [64]:
#vstack은 위아래로 연결한다,

np.vstack([a1,a2])

array([[1., 1.],
       [1., 1.],
       [0., 0.],
       [0., 0.]])

In [65]:
#dstack은 제3의 축 , 깊이 방향으로 배열을 합친다 ->>
c1 = np.ones((3, 4))
c1

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [66]:
c2 = np.zeros((3, 4))
c2

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [67]:
np.dstack([c1, c2])

array([[[1., 0.],
        [1., 0.],
        [1., 0.],
        [1., 0.]],

       [[1., 0.],
        [1., 0.],
        [1., 0.],
        [1., 0.]],

       [[1., 0.],
        [1., 0.],
        [1., 0.],
        [1., 0.]]])

In [68]:
(np.dstack([c1, c2])).shape

(3, 4, 2)

In [70]:
np.r_[np.array([1, 2, 3]), np.array([4, 5, 6])]
#가로로 붙임 ,대신에 대괄호가 사용됨

array([1, 2, 3, 4, 5, 6])

In [111]:
#차원을 증가시킨후 좌우 연결
x=np.c_[np.array([1, 2, 3]), np.array([4, 5, 6])]
x.ndim

2

In [73]:
#tile은 동일한 배열을 반복하여 연결한다
a = np.array([[0, 1, 2], [3, 4, 5]])
np.tile(a, 2)

array([[0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5]])

# 연습문제 4.1.4

In [78]:

a=np.array([0,0,0,1,1])
a

array([0, 0, 0, 1, 1])

In [79]:
b=np.vstack([a,a,a])

In [123]:
b

array([[0, 0, 0, 1, 1],
       [0, 0, 0, 1, 1],
       [0, 0, 0, 1, 1]])

In [124]:
 
c=np.arange(10, 160, 10)
c = c.reshape(3,5)
c

array([[ 10,  20,  30,  40,  50],
       [ 60,  70,  80,  90, 100],
       [110, 120, 130, 140, 150]])

In [127]:
n=np.vstack([b,c])

In [128]:
m=np.vstack([n,n])

In [129]:
m

array([[  0,   0,   0,   1,   1],
       [  0,   0,   0,   1,   1],
       [  0,   0,   0,   1,   1],
       [ 10,  20,  30,  40,  50],
       [ 60,  70,  80,  90, 100],
       [110, 120, 130, 140, 150],
       [  0,   0,   0,   1,   1],
       [  0,   0,   0,   1,   1],
       [  0,   0,   0,   1,   1],
       [ 10,  20,  30,  40,  50],
       [ 60,  70,  80,  90, 100],
       [110, 120, 130, 140, 150]])

In [130]:
#그리드 포인트
x = np.arange(3)
x

array([0, 1, 2])

In [131]:
y = np.arange(5)
y

array([0, 1, 2, 3, 4])

In [132]:
#변수가 두개이고 이것이 2차원으로 그려질때 각 변수들이 변화하는 점을 볼 수 있게 해준다.

In [133]:
X, Y = np.meshgrid(x, y)

In [134]:
X

array([[0, 1, 2],
       [0, 1, 2],
       [0, 1, 2],
       [0, 1, 2],
       [0, 1, 2]])

In [135]:
Y

array([[0, 0, 0],
       [1, 1, 1],
       [2, 2, 2],
       [3, 3, 3],
       [4, 4, 4]])

In [136]:
[list(zip(x, y)) for x, y in zip(X, Y)]

[[(0, 0), (1, 0), (2, 0)],
 [(0, 1), (1, 1), (2, 1)],
 [(0, 2), (1, 2), (2, 2)],
 [(0, 3), (1, 3), (2, 3)],
 [(0, 4), (1, 4), (2, 4)]]

In [139]:
import matplotlib.pylab as plt
plt.title("np.meshgrid로 만든 Grid Points")
plt.scatter(X, Y, linewidths=10)
plt.show()

<Figure size 640x480 with 1 Axes>