# 파이썬 패키지 사용하기


In [1]:
import sklearn as sk

In [ ]:
#dir을 쓰면  패키지안에 내장되어 있는 함수를 볼수 있다.

In [2]:
dir(sk)
#이것을 쓰면 google에 detection하기 쉬울것 같다.

['_ASSUME_FINITE',
 '__SKLEARN_SETUP__',
 '__all__',
 '__builtins__',
 '__cached__',
 '__check_build',
 '__doc__',
 '__file__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '__version__',
 '_contextmanager',
 'base',
 'clone',
 'config_context',
 'exceptions',
 'externals',
 'get_config',
 'logger',
 'logging',
 'os',
 're',
 'set_config',
 'setup_module',
 'sys',
 'utils',
 'warnings']

# 보통 패키지는 안에 하위패키지를 가지고 있다.
# 패키지가 알아서 깔릴수도 있지만 일일이 따로 import해줘야 되는 경우도 있다

In [3]:
import sklearn.preprocessing

In [4]:
dir(sklearn.preprocessing)

['Binarizer',
 'FunctionTransformer',
 'Imputer',
 'KernelCenterer',
 'LabelBinarizer',
 'LabelEncoder',
 'MaxAbsScaler',
 'MinMaxScaler',
 'MultiLabelBinarizer',
 'Normalizer',
 'OneHotEncoder',
 'PolynomialFeatures',
 'QuantileTransformer',
 'RobustScaler',
 'StandardScaler',
 '__all__',
 '__builtins__',
 '__cached__',
 '__doc__',
 '__file__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '_function_transformer',
 'add_dummy_feature',
 'binarize',
 'data',
 'imputation',
 'label',
 'label_binarize',
 'maxabs_scale',
 'minmax_scale',
 'normalize',
 'quantile_transform',
 'robust_scale',
 'scale']

In [6]:
#패키지의 포함된 함수를 사용하려면 as 뒤에 쓴 이름뒤에 .을 쓰고 함수 이름을 쓰면된다
import numpy as np
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
#패키지를 임포트 할때 특정한 명령어들만 선택적으로 임포트 할 수 있다.
from numpy import arange

In [8]:
from numpy import arange
arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
#위의 6과는 다른게 import를 전부다하기 때문에 메모리를 많이 잡아먹는다.
from numpy import *

In [10]:
arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
#이것의 안좋은점에 메모리를 많이 먹는 것도 있지만 원래 정의 되어 있는 함수를 덮어써 버릴수도 있다.
from numpy import arange
arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
#ex)
def f():
    print("I am f function!")

In [13]:
f()

I am f function!


In [14]:
from scipy.stats import *

In [15]:
#요렇게 된다.
f()

TypeError: _parse_args() missing 2 required positional arguments: 'dfn' and 'dfd'