# 난수 발생과 카운팅

In [2]:
#랜덤으로 숫자를 발생시키는 방법은 numpy random패키지에서 볼수 있다
#생성된 난수는 다음번 난수 생성을 위한 시드값이 된다.  -> 무작정 막 랜덤으로 뽑는 것이 아님   정해진 알고리즘으로 숫자를 뽑음 앞에 
#숫자가 뒷숫자에 영향을 끼침
#파이썬의 시드를 설정하는 명령은 seed이다 0이나 0보다 큰 정수를 넣어준다
import numpy as np

In [5]:
np.random.seed(0)
np.random.rand(5)    #처음 돌렸을 때 나오는 난수는 예제와 같은 걸 보니 정해진 알고리즘으로 나오는게 맞는거 같다.

array([0.5488135 , 0.71518937, 0.60276338, 0.54488318, 0.4236548 ])

In [8]:
np.random.rand(10)

array([0.0871293 , 0.0202184 , 0.83261985, 0.77815675, 0.87001215,
       0.97861834, 0.79915856, 0.46147936, 0.78052918, 0.11827443])

In [11]:
np.random.seed(0)
np.random.rand(5)
#0으로 seed를 초기화 시킨 다음 다시 돌리면 앞에 결과값과 똑같은 숫자가 나온다

array([0.5488135 , 0.71518937, 0.60276338, 0.54488318, 0.4236548 ])

In [13]:
#데이터의 순서를 바꾸려면 shuffle 명령을 사용한다
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
np.random.shuffle(x)
x

array([0, 8, 7, 9, 1, 3, 5, 2, 4, 6])

# 데이터 샘플링

In [16]:
#데이터를 샘플링 할때는 numpy.random.choice(a, size=None, replace=True, p=None) 을 쓸 수 있다.
#a 배열이면 원래데이터, 정수면 arange(a)로 생성
#size 정수, 샘플 숫자
#replace ture이면 중복 샘플링 가능
#p   배열 각데이터가 선택될수 있는 확률

In [23]:
np.random.choice(10,5,replace=True)

array([3, 8, 1, 3, 3])

In [25]:
np.random.choice(5, 10)  # 반복해서 10개 선택    #데이터 개수를 넘어가면 자동으로 replace=True가 되는 듯 하다

array([2, 4, 2, 0, 0, 4, 0, 4, 1, 4])

In [27]:
np.random.choice(5, 10, p=[0.1, 0, 0.3, 0.6, 0])  # 선택 확률을 다르게 해서 10개 선택
#2와 3의 확률이 높아서 더 많이 뽑힌 것을 볼 수 있다.

array([2, 3, 3, 3, 2, 2, 2, 3, 2, 3], dtype=int64)

# 난수 생성

In [28]:
np.random.rand(10)

array([0.24442559, 0.15896958, 0.11037514, 0.65632959, 0.13818295,
       0.19658236, 0.36872517, 0.82099323, 0.09710128, 0.83794491])

In [30]:
np.random.rand(3, 5)
#3행 5열로 뽑기

array([[0.56660145, 0.26538949, 0.52324805, 0.09394051, 0.5759465 ],
       [0.9292962 , 0.31856895, 0.66741038, 0.13179786, 0.7163272 ],
       [0.28940609, 0.18319136, 0.58651293, 0.02010755, 0.82894003]])

In [31]:
#rand: 0부터 1사이의 균일 분포
#randn: 가우시안 표준 정규 분포
#randint: 균일 분포의 정수 난수
np.random.randn(10)

array([ 0.92525075, -0.90478616,  1.84369153,  1.52550724, -1.44553558,
        0.37716061, -0.07055723,  0.60415971,  0.472149  ,  0.81991729])

In [35]:
#randint는 정수를 난수로 배출하고 다음과 같은 인수를 가진다.   
#np.random.randint(low, high=None, size=None)
np.random.randint(10, size=10)
#high가 10, 10개의 개수 난수 생성

array([9, 1, 6, 8, 8, 3, 2, 3, 6, 3])

In [37]:
np.random.randint(10, 20, size=(3, 5))


array([[14, 15, 13, 13, 17],
       [19, 19, 19, 17, 13],
       [12, 13, 19, 17, 17]])

# 정수 데이터 카운팅

In [38]:
#unique는 데이터 안의 중복값 제거 하고 출력한다
np.unique([11,11,11,11,11])

array([11])

In [39]:
a = np.array(['a', 'b', 'b', 'c', 'a'])
index, count = np.unique(a, return_counts=True)

In [40]:
index

array(['a', 'b', 'c'], dtype='<U1')

In [41]:
count

array([2, 2, 1], dtype=int64)

In [45]:
#unique같은 경우에는 예를들어 주사위6번 던졌을 때 각 숫자가 나올 횟수를 구한다고 하면 한번도 나오지 않는 숫자에는 정보를 주지않는다
#그렇기 때문에 해당의 경우 bincount에 minlength인수를 설정하여 쓰는 것이 더 편리하다.
np.bincount([2,3,1,3],minlength=6)
#1이 1번 2가 1번 3이 2번 나왔다는 의미

array([0, 1, 1, 2, 0, 0], dtype=int64)